// 소비자에게는 의존성이 없는 ES 모듈 하나를 제공한다. 외부 번들러는 사용하지 않는다.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const entry=fs.readFileSync(path.join(root,'src/index.js'),'utf8');
const publicNames=new Set([...entry.matchAll(/export\s*\{([^}]+)\}/g)].flatMap(m=>m[1].split(',').map(n=>n.trim())));
const visited=new Set(),chunks=[];
function visit(file){
  if(visited.has(file))return;visited.add(file);
  const source=fs.readFileSync(path.join(root,'src',file),'utf8').replace(/\r\n/g,'\n');
  for(const m of source.matchAll(/^(?:import|export)[^\n]*\bfrom\s+['"]\.\/([^'"]+)['"];?$/gm))visit(m[1]);
  if(file==='index.js')return;
  let body=source.replace(/^import[^\n]*\bfrom\s+['"][^'"]+['"];?\n/gm,'');
  body=body.replace(/^export\s+((?:(?:async\s+)?function|const|class)\s+(\w+))/gm,(_,decl,name)=>publicNames.has(name)?'export '+decl:decl);
  if(/^(?:import|export\s*\{|export\s*\*)/m.test(body))throw Error('Unsupported bundle syntax: '+file);
  chunks.push('// src/'+file+'\n'+body.trim());
}
visit('index.js');
const bundle='/** Generated by scripts/build.mjs from src/. Development SSOT: CONTRACT.md. */\n'+chunks.join('\n\n')+'\n';
const target=path.join(root,'rollback-netcode.js');
if(process.argv.includes('--check')){
  if(fs.readFileSync(target,'utf8').replace(/\r\n/g,'\n')!==bundle)throw Error('rollback-netcode.js is stale; run node scripts/build.mjs');
  console.log('PASS: single-module artifact matches source');
}else{fs.writeFileSync(target,bundle);console.log('Generated rollback-netcode.js ('+Buffer.byteLength(bundle)+' bytes)')}
